on: [push]

name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Make the script file executable (OpenBLAS install)
        run: chmod +x .github/install_openblas.bash
      - name: Run the script (Install OpenBLAS)
        run: |
          .github/install_openblas.bash
      - name: Build the Rust executable
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

